apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-nginx
data:
  default.conf: |
    server {
      listen 8080;
      location / {
        proxy_pass http://vote.default.svc.cluster.local:80;
      }
    }

    server {
      listen 8081;
      location / {
        proxy_pass http://result.default.svc.cluster.local:80;
      }
    }
